// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9uBRGy24DXqKJPl9jR0uISsrNDi8TQkM',
    appId: '1:255585781293:web:98ec0ada5781dbd907daa4',
    messagingSenderId: '255585781293',
    projectId: 'proespotrsarena',
    authDomain: 'proespotrsarena.firebaseapp.com',
    storageBucket: 'proespotrsarena.firebasestorage.app',
    measurementId: 'G-03SEFD1R17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOBjxABsB7GaWxKm7qoPopazchB-JJJlM',
    appId: '1:255585781293:android:d44a68d942996c3507daa4',
    messagingSenderId: '255585781293',
    projectId: 'proespotrsarena',
    storageBucket: 'proespotrsarena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7uyAHLttRfu1bDlFNrVtxKApVHWqUq3g',
    appId: '1:255585781293:ios:5726becd8047186507daa4',
    messagingSenderId: '255585781293',
    projectId: 'proespotrsarena',
    storageBucket: 'proespotrsarena.firebasestorage.app',
    iosBundleId: 'com.example.esportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7uyAHLttRfu1bDlFNrVtxKApVHWqUq3g',
    appId: '1:255585781293:ios:5726becd8047186507daa4',
    messagingSenderId: '255585781293',
    projectId: 'proespotrsarena',
    storageBucket: 'proespotrsarena.firebasestorage.app',
    iosBundleId: 'com.example.esportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9uBRGy24DXqKJPl9jR0uISsrNDi8TQkM',
    appId: '1:255585781293:web:dddc2efda837440007daa4',
    messagingSenderId: '255585781293',
    projectId: 'proespotrsarena',
    authDomain: 'proespotrsarena.firebaseapp.com',
    storageBucket: 'proespotrsarena.firebasestorage.app',
    measurementId: 'G-25GKMG0B4Y',
  );
}
